### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by iKamus** [3n-k1/build-aseprite#1]
When try it it give error like this "Error: invalid module name: build-aseprite"
and when change name to build aseprite it give this other error "Error: cannot open 'build.nim'"

**Comment by 3n-k1** [comment]
Oh shit, I'm sorry I never saw this! I renamed and pushed without checking that dashes were allowed in Nim filenames. I've since changed it to an underscore and it should work now.

I'll be honest, I didn't expect anyone else to ever use this haha. Thanks for checking it out, and feel free to try again, it works now :P
